name: Deploy Portfolio to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{  secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.MY_PORTFOLIO_PROJECT_ID }}

      - name: Configure Docker Authentication
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="asia-south1-docker.pkg.dev/${{ secrets.MY_PORTFOLIO_PROJECT_ID }}/cloud-run/portfolio"
          docker build -t "$IMAGE_NAME" .
          docker push "$IMAGE_NAME"

      - name: Deploy portfolio to Cloud Run  
        run: |
          gcloud run deploy portfolio-service \
            --image=asia-south1-docker.pkg.dev/${{ secrets.MY_PORTFOLIO_PROJECT_ID }}/cloud-run/portfolio \
            --region=asia-south1 \
            --platform=managed \
            --allow-unauthenticated \
            --port=8080
